Rails.application.routes.draw do
  resources :sellers, only: [:new, :create]
  resources :payers, only: [:new, :create]
  resources :operations, only: [:new, :show]
  resources :invoices, only: [:new, :create]
  post '/invoices/load_xml', to: 'invoices#load_invoice_from_xml'

  devise_for :users
  root to: 'pages#home'
  post '/cnpj_check', to: 'cnpj_checks#fetch_information'

  # FT routes
   # All routes
  # get "ft/dashboards/dashboard_1"
  # get "ft/dashboards/dashboard_2"
  # get "ft/dashboards/dashboard_3"
  # get "ft/dashboards/dashboard_4"
  # get "ft/dashboards/dashboard_4_1"
  # get "ft/dashboards/dashboard_5"

  # get "ft/layoutsoptions/index"
  # get "ft/layoutsoptions/off_canvas"

  # get "ft/graphs/flot"
  # get "ft/graphs/morris"
  # get "ft/graphs/rickshaw"
  # get "ft/graphs/chartjs"
  # get "ft/graphs/chartist"
  # get "ft/graphs/peity"
  # get "ft/graphs/sparkline"
  # get "ft/graphs/c3charts"

  # get "ft/mailbox/inbox"
  # get "ft/mailbox/email_view"
  # get "ft/mailbox/compose_email"
  # get "ft/mailbox/email_templates"
  # get "ft/mailbox/basic_action_email"
  # get "ft/mailbox/alert_email"
  # get "ft/mailbox/billing_email"

  # get "ft/metrics/index"

  # get "ft/widgets/index"

  # get "ft/forms/basic_forms"
  # get "ft/forms/advanced"
  # get "ft/forms/wizard"
  # get "ft/forms/file_upload"
  # get "ft/forms/text_editor"
  # get "ft/forms/autocomplete"
  # get "ft/forms/markdown"

  # get "ft/appviews/contacts"
  # get "ft/appviews/profile"
  # get "ft/appviews/profile_two"
  # get "ft/appviews/contacts_two"
  # get "ft/appviews/projects"
  # get "ft/appviews/project_detail"
  # get "ft/appviews/activity_stream"
  # get "ft/appviews/file_menager"
  # get "ft/appviews/vote_list"
  # get "ft/appviews/calendar"
  # get "ft/appviews/faq"
  # get "ft/appviews/timeline"
  # get "ft/appviews/pin_board"
  # get "ft/appviews/teams_board"
  # get "ft/appviews/social_feed"
  # get "ft/appviews/clients"
  # get "ft/appviews/outlook_view"
  # get "ft/appviews/blog"
  # get "ft/appviews/article"
  # get "ft/appviews/issue_tracker"

  # get "ft/pages/search_results"
  # get "ft/pages/lockscreen"
  # get "ft/pages/invoice"
  # get "ft/pages/invoice_print"
  # get "ft/pages/login"
  # get "ft/pages/login_2"
  # get "ft/pages/forgot_password"
  # get "ft/pages/register"
  # get "ft/pages/not_found_error"
  # get "ft/pages/internal_server_error"
  # get "ft/pages/empty_page"

  # get "ft/miscellaneous/notification"
  # get "ft/miscellaneous/nestablelist"
  # get "ft/miscellaneous/timeline_second_version"
  # get "ft/miscellaneous/forum_view"
  # get "ft/miscellaneous/forum_post_view"
  # get "ft/miscellaneous/google_maps"
  # get "ft/miscellaneous/datamaps"
  # get "ft/miscellaneous/social_buttons"
  # get "ft/miscellaneous/code_editor"
  # get "ft/miscellaneous/modal_window"
  # get "ft/miscellaneous/validation"
  # get "ft/miscellaneous/tree_view"
  # get "ft/miscellaneous/chat_view"
  # get "ft/miscellaneous/agile_board"
  # get "ft/miscellaneous/diff"
  # get "ft/miscellaneous/pdf_viewer"
  # get "ft/miscellaneous/sweet_alert"
  # get "ft/miscellaneous/idle_timer"
  # get "ft/miscellaneous/spinners"
  # get "ft/miscellaneous/spinners_usage"
  # get "ft/miscellaneous/live_favicon"
  # get "ft/miscellaneous/masonry"
  # get "ft/miscellaneous/tour"
  # get "ft/miscellaneous/loading_buttons"
  # get "ft/miscellaneous/clipboard"
  # get "ft/miscellaneous/text_spinners"
  # get "ft/miscellaneous/truncate"
  # get "ft/miscellaneous/password_meter"
  # get "ft/miscellaneous/i18support"

  # get "ft/uielements/typography"
  # get "ft/uielements/icons"
  # get "ft/uielements/draggable_panels"
  # get "ft/uielements/resizeable_panels"
  # get "ft/uielements/buttons"
  # get "ft/uielements/video"
  # get "ft/uielements/tables_panels"
  # get "ft/uielements/tabs"
  # get "ft/uielements/notifications_tooltips"
  # get "ft/uielements/helper_classes"
  # get "ft/uielements/badges_labels_progress"

  # get "ft/gridoptions/index"

  # get "ft/tables/static_tables"
  # get "ft/tables/data_tables"
  # get "ft/tables/foo_tables"
  # get "ft/tables/jqgrid"

  # get "ft/commerce/products_grid"
  # get "ft/commerce/products_list"
  # get "ft/commerce/product_edit"
  # get "ft/commerce/product_detail"
  # get "ft/commerce/orders"
  # get "ft/commerce/cart"
  # get "ft/commerce/payments"

  # get "ft/gallery/basic_gallery"
  # get "ft/gallery/slick_carusela"
  # get "ft/gallery/bootstrap_carusela"

  # get "ft/cssanimations/index"

  # get "ft/landing/index"

   # All routes

   namespace :ft do
    get "dashboards/dashboard_1"
    get "dashboards/dashboard_2"
    get "dashboards/dashboard_3"
    get "dashboards/dashboard_4"
    get "dashboards/dashboard_4_1"
    get "dashboards/dashboard_5"

    get "layoutsoptions/index"
    get "layoutsoptions/off_canvas"

    get "graphs/flot"
    get "graphs/morris"
    get "graphs/rickshaw"
    get "graphs/chartjs"
    get "graphs/chartist"
    get "graphs/peity"
    get "graphs/sparkline"
    get "graphs/c3charts"

    get "mailbox/inbox"
    get "mailbox/email_view"
    get "mailbox/compose_email"
    get "mailbox/email_templates"
    get "mailbox/basic_action_email"
    get "mailbox/alert_email"
    get "mailbox/billing_email"

    get "metrics/index"

    get "widgets/index"

    get "forms/basic_forms"
    get "forms/advanced"
    get "forms/wizard"
    get "forms/file_upload"
    get "forms/text_editor"
    get "forms/autocomplete"
    get "forms/markdown"

    get "appviews/contacts"
    get "appviews/profile"
    get "appviews/profile_two"
    get "appviews/contacts_two"
    get "appviews/projects"
    get "appviews/project_detail"
    get "appviews/activity_stream"
    get "appviews/file_menager"
    get "appviews/vote_list"
    get "appviews/calendar"
    get "appviews/faq"
    get "appviews/timeline"
    get "appviews/pin_board"
    get "appviews/teams_board"
    get "appviews/social_feed"
    get "appviews/clients"
    get "appviews/outlook_view"
    get "appviews/blog"
    get "appviews/article"
    get "appviews/issue_tracker"

    get "pages/search_results"
    get "pages/lockscreen"
    get "pages/invoice"
    get "pages/invoice_print"
    get "pages/login"
    get "pages/login_2"
    get "pages/forgot_password"
    get "pages/register"
    get "pages/not_found_error"
    get "pages/internal_server_error"
    get "pages/empty_page"

    get "miscellaneous/notification"
    get "miscellaneous/nestablelist"
    get "miscellaneous/timeline_second_version"
    get "miscellaneous/forum_view"
    get "miscellaneous/forum_post_view"
    get "miscellaneous/google_maps"
    get "miscellaneous/datamaps"
    get "miscellaneous/social_buttons"
    get "miscellaneous/code_editor"
    get "miscellaneous/modal_window"
    get "miscellaneous/validation"
    get "miscellaneous/tree_view"
    get "miscellaneous/chat_view"
    get "miscellaneous/agile_board"
    get "miscellaneous/diff"
    get "miscellaneous/pdf_viewer"
    get "miscellaneous/sweet_alert"
    get "miscellaneous/idle_timer"
    get "miscellaneous/spinners"
    get "miscellaneous/spinners_usage"
    get "miscellaneous/live_favicon"
    get "miscellaneous/masonry"
    get "miscellaneous/tour"
    get "miscellaneous/loading_buttons"
    get "miscellaneous/clipboard"
    get "miscellaneous/text_spinners"
    get "miscellaneous/truncate"
    get "miscellaneous/password_meter"
    get "miscellaneous/i18support"

    get "uielements/typography"
    get "uielements/icons"
    get "uielements/draggable_panels"
    get "uielements/resizeable_panels"
    get "uielements/buttons"
    get "uielements/video"
    get "uielements/tables_panels"
    get "uielements/tabs"
    get "uielements/notifications_tooltips"
    get "uielements/helper_classes"
    get "uielements/badges_labels_progress"

    get "gridoptions/index"

    get "tables/static_tables"
    get "tables/data_tables"
    get "tables/foo_tables"
    get "tables/jqgrid"

    get "commerce/products_grid"
    get "commerce/products_list"
    get "commerce/product_edit"
    get "commerce/product_detail"
    get "commerce/orders"
    get "commerce/cart"
    get "commerce/payments"

    get "gallery/basic_gallery"
    get "gallery/slick_carusela"
    get "gallery/bootstrap_carusela"

    get "cssanimations/index"

    get "landing/index"
  end

end
